Add bookings
kompasvideo/java-shareit pull request #4
Opened 2022-08-13 10:45 UTC by kompasvideo

2022-08-15 05:55 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-08-15 05:55 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from Booking as b" +
А зачем на SQL, вся фишка ORM в том, что он позволяет запросы писать
а) более просто
б) самое главное - независимо от целевой СУБД, чего не получится сделать на sql, так как его диалекты отличаются в зависимости от производителя :)

Попробуй хотя бы один запрос переписать, если получится то гут :)

2022-08-15 05:55 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved.equals(Boolean.TRUE)) {
Один и тот же код дублируется, отличается только статус, думаю можно сначала в условии вычислить статус, а сохранение везде одинаково :)

2022-08-15 05:55 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookings.forEach(booking -> bookingsDto.add(BookingMapper.toBookingDto(booking,
Чет слишком много уж всего тут творится, давай все таки сделаем попроще, внутри forEach пусть каждая логическая операция будет в отдельной строке а не единой кашей все :)

itemRepository.findById(booking.getItemId()).get().getName())

Можно переписать, кстати, двумя способами (и избежать возможного NullPointerException)
1.
Optional.ofNullable(itemRepository.findById(booking.getItemId())).ifPresent( (item)->{  ... });

2.
Optional.ofNullable(itemRepository.findById(booking.getItemId())).map(Item::getName).orElse("");

2022-08-15 05:55 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            .findById(bookingRepository
Не стоит так вкладывать вызовы, нагромождение вызовов в БД, распаковки Optional и пр ;)

2022-08-15 05:55 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/item/ItemServiceImpl.java
> +        return CommentMapper.toCommentDto(comment, userRepository.findById(userId).get().getName());
Объект, который производит маппинг можно так же сделать отдельным бином. Это позволит спрятать, во первых, все настройки маппинга (в нашем учебном примере они тривиальны, но может быть и гораздо сложнее), во вторых - на такой сервис можно написать отдельный тест, проверяющий что поля складываются как надо :)

2022-08-16 04:35 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved.equals(Boolean.TRUE)) {
сделано

2022-08-16 05:06 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/item/ItemServiceImpl.java
> +        return CommentMapper.toCommentDto(comment, userRepository.findById(userId).get().getName());
сделано

2022-08-16 19:16 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookings.forEach(booking -> bookingsDto.add(BookingMapper.toBookingDto(booking,
сделано

2022-08-16 19:25 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            .findById(bookingRepository
сделано

2022-08-16 19:26 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from Booking as b" +
как раз один запрос удалось переписать

2022-08-16 20:28 UTC, TyutterinYakov reviewed
Добрый вечер! В целом - хорошо) Отметил некоторые недочеты, которые следует исправить) Хорошего вечера! Если возникнут вопросы - пиши в слак, буду рад помочь :)

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
(предложение)Можно добавить такую аннотацию
@NoArgsConstructor(access = AccessLevel.PRIVATE)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Предложение - можно было бы по дефолту использовать транзакцию вида
@Transactional(readOnly = true)
А там, где уже будет требоваться сохранение - просто переопределить ее, добавив аннотацию над методом)

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
Фильтрацию данных следует производить на уровне бд, так как это менее затратно. Иначе мы сначала отправляем запрос на извлечение большого количества данных, а потом еще с ним работаем. Лучше произвести фильтрацию на уровне бд, так как на ее уровне это будет произведено в разы быстрее)
Метод будет выглядеть примерно так)
findByBookerIdAndEndIsBefore

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
аналогично и здесь, фильтрацию следует произвести на уровне БД

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
аналогично и здесь, фильтрацию следует произвести на уровне БД

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
аналогично и здесь, фильтрацию следует произвести на уровне БД

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
аналогично и здесь, фильтрацию следует произвести на уровне БД

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                    if (booking.getEnd().isAfter(LocalDateTime.now())) {
аналогично и здесь, фильтрацию следует произвести на уровне БД

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking, BookingDto.Item item, BookingDto.Book booker) {
Более корректно было бы принимать User'a и Item из классов-моделей, а уже потом преобразовывать их к BookingDto.Book и BookingDto.Item. Таким образом мы избавимся от дублирования кода в сервисе и упростим логику

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final ValidationException e) {
Ошибки валидации должны иметь статус 400 BAD_REQUEST

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +     * Other exception
Так же должен быть общий обработчик для всех других непроверяемых исключений) Этот хендлер будет принимать Throwable)

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/item/model/Item.java
> +    private Long ownerId;
Можно было бы добавить связь с таблицей пользователей)
	@ManyToOne(optional = false)
	@JoinColumn(name = "owner_id", nullable = false)
	private User owner;
Чтобы мы сразу же могли вытащить пользователя из вещи

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/item/model/Comment.java
> +    private Long itemId;
Аналогично и здесь)
Можно было бы связать комментарий с предметом и пользователем, используя аннотации
	@ManyToOne
	@JoinColumn(name = "...")

2022-08-16 20:28 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    LocalDateTime start;
Для соблюдения инкапсуляции поля класса должны быть приватными

2022-08-16 21:13 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
добавил

2022-08-16 21:13 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
добавил

2022-08-17 09:39 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
сделано

2022-08-17 09:39 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
сделано

2022-08-17 10:03 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
сделано

2022-08-17 10:07 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
сделано

2022-08-17 10:11 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
сделано

2022-08-17 10:19 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
сделаано

2022-08-17 10:20 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                for (Booking booking : bookings) {
сделано

2022-08-17 10:20 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                    if (booking.getEnd().isAfter(LocalDateTime.now())) {
сделано

2022-08-17 10:21 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking, BookingDto.Item item, BookingDto.Book booker) {
класс удалён, сделано всё через Bean в ShareItApp.java

2022-08-17 10:23 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final ValidationException e) {
Изменено имя класса

2022-08-17 10:48 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +     * Other exception
сделано

2022-08-17 16:30 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/item/model/Item.java
> +    private Long ownerId;
сделано

2022-08-17 16:33 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/item/model/Comment.java
> +    private Long itemId;
сделано

2022-08-17 16:34 UTC, kompasvideo commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    LocalDateTime start;
сделано

2022-08-17 18:25 UTC, TyutterinYakov approved these changes
Добрый вечер! Поздравляю с успешной сдачей спринта! Сил и терпения на этом нелегком, но интересном пути) Доброй ночи😇

2022-08-21 11:58 UTC, merged